name: curso_de_verano
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  go_router: ^14.7.2
  cloud_firestore: ^5.6.2
  camera: ^0.11.1
  permission_handler: ^11.3.1
  firebase_storage: ^12.4.2
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.9+1
  encrypt: ^5.0.3
  carousel_slider: ^5.0.0
  firebase_messaging: ^15.2.2
  firebase_analytics: ^11.4.2
  firebase_crashlytics: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
